// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPhFdFKy3FxN7YVwdmBJl9d6IDin6STR4',
    appId: '1:357850324536:web:bfccf1ae608f6be31890cd',
    messagingSenderId: '357850324536',
    projectId: 'chat-app-41ff6',
    authDomain: 'chat-app-41ff6.firebaseapp.com',
    storageBucket: 'chat-app-41ff6.firebasestorage.app',
    measurementId: 'G-E1TEFFMZSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgGy3BcoxRz4_IBo2Hamt5akGYZvVs-WQ',
    appId: '1:357850324536:android:250fd9c97c56eb8b1890cd',
    messagingSenderId: '357850324536',
    projectId: 'chat-app-41ff6',
    storageBucket: 'chat-app-41ff6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqvpdo1L8VxVzh3rlkjnY2bMmNmoUzGPM',
    appId: '1:357850324536:ios:53755c4f2badbacd1890cd',
    messagingSenderId: '357850324536',
    projectId: 'chat-app-41ff6',
    storageBucket: 'chat-app-41ff6.firebasestorage.app',
    iosBundleId: 'com.example.nhom53Excersise2Chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqvpdo1L8VxVzh3rlkjnY2bMmNmoUzGPM',
    appId: '1:357850324536:ios:53755c4f2badbacd1890cd',
    messagingSenderId: '357850324536',
    projectId: 'chat-app-41ff6',
    storageBucket: 'chat-app-41ff6.firebasestorage.app',
    iosBundleId: 'com.example.nhom53Excersise2Chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPhFdFKy3FxN7YVwdmBJl9d6IDin6STR4',
    appId: '1:357850324536:web:f665ab525f2c54e01890cd',
    messagingSenderId: '357850324536',
    projectId: 'chat-app-41ff6',
    authDomain: 'chat-app-41ff6.firebaseapp.com',
    storageBucket: 'chat-app-41ff6.firebasestorage.app',
    measurementId: 'G-LQK6X9WGEG',
  );
}
